const houses = [
    {
    name:"Claremont Home",
    price:15000,
    location:"Claremont Home,18 Kubrick Street",
    bedrooms:3,
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/pexels-(2).jpg'},{url:'/images/pexels-(3).jpg'},{url:'/images/pexels-(4).jpg'},{url:'/images/pexels-(5).jpg'},{url:'/images/pexels-(6).jpg'},{url:'/images/pexels-(7).jpg'},{url:'/images/pexels-(8).jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/pexels-(1).jpg'
},
{
    name:"Palm Stead",
    location:"Palm Stead,Perm gardens",
    price:15000,
    bedrooms:3,
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/03bee317-c-2-EXT.jpg'},{url:'/images/03bee317-c-3-EXT.jpg'},{url:'/images/03bee317-c-4-EXT.jpg'},{url:'/images/03bee317-c-5-EXT.jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/03bee317-c-1-EXT.jpg'
},
{
    name:"Somerset West",
    price:15000,
    bedrooms:3,
    location:"Cape Town,Somerset West",
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/house-austr-2.jpg'},{url:'/images/house-austr-3.jpg'},{url:'/images/house-austr-4.jpg'},{url:'/images/house-austr-5.jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/house-austr.jpg'
},
{
    name:"New Orleans",
    price:15000,
    bedrooms:3,
    location:"Cape Town,12 Stanley Street",
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/parklane- (2).jpg'},{url:'/images/parklane- (3).jpg'},{url:'/images/parklane- (4).jpg'},{url:'/images/parklane- (5).jpg'},{url:'/images/parklane- (6).jpg'},{url:'/images/parklane- (7).jpg'},{url:'/images/parklane- (8).jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/parklane- (1).jpg'
},

{
   name:"New Orleans",
   price:15000,
    bedrooms:3,
    location:"Cape Town,12 Stanley Street",
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/582723_15-EXT.jpg'},{url:'/images/582723_11-REPLACE.jpg'},{url:'/images/582723_8-REPLACE.jpg'},{url:'/images/582723_6-REPLACE.jpg'},{url:'/images/582723_2-REPLACE.jpg'},{url:'/images/582723_1-REPLACE.jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/582723_1-REPLACE.jpg'
},
{
    name:"The Epitome Of Luxury Meeting Nature In South Africa",
    price:15000,
    location:"Campbs Bay,Upper Street",
    bedrooms:3,
    bathrooms:4,
    noOfCars:4,
    description:"This House IS The Bomb",
    size:562,
    garden:true,
    pool:true,
    petFriendly:true,
    images:[{url:'/images/pexels-(2).jpg'},{url:'/images/pexels-(3).jpg'},{url:'/images/pexels-(4).jpg'},{url:'/images/pexels-(5).jpg'},{url:'/images/pexels-(6).jpg'},{url:'/images/pexels-(7).jpg'},{url:'/images/pexels-(8).jpg'}],
    propertyType:"House",
    streetAddress:"12 Stanley Street",
    coverImage:'/images/pexels-(1).jpg'
}

]

module.exports = houses;